evaluacion1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('joyeria.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

joyeria/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView
app_name = 'tienda'

urlpatterns = [
    path('', views.index, name='index'),
#Productos
    # Categorias
    path('categorias/', views.ListarCategorias, name='listar_categorias'),
    path('categorias-agregar/', views.AgregarCategoria, name='agregar_categoria'),
    path('categorias/<str:nombre>/modificar/', views.ModificarCategoria, name='modificar_categoria'),  # Cambia de slug a nombre
    path('categorias/<str:nombre>/', views.eliminar_categorias, name='eliminar_categorias'),  # Cambia de slug a nombre
    
    # Productos
    path('producto/<str:nombre>/', views.detalleProducto, name='producto'), 
    path('listar-productos/', views.listar_productos, name='listar_productos'),
    path('agregar-productos/', views.agregar_producto, name='agregar_producto'),
    path('eliminar-productos/<str:nombre>/', views.eliminar_producto, name='eliminar_producto'),  
    path('modificar-productos/<str:nombre>/', views.modificar_producto, name='modificar_producto'),  
    path('productocategoria/<str:nombre>/', views.productoxCategoria, name='productocategoria'), 

#inicio y registro de usuario
    path('registrar/', views.registro, name='registrar'),
    path('login/', views.iniciar_sesion, name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

#carro de compras

    path('addtocart/<int:producto_id>/', views.add_to_cart, name='addtocart'),
    path('cart/', views.cart_page, name='cart'),
    path('procesar_pedido/', views.procesar_pedido, name='procesar_pedido'),
    path('lista-pedidos/', views.lista_pedidos, name='lista_pedidos'),
    path('materiales/', views.mostrar_materiales, name='mostrar_materiales'),
    path('materiales/agregar/', views.agregar_material, name='agregar_material'),
    path('materiales/editar/<int:material_id>/', views.editar_material, name='editar_material'),
    path('materiales/eliminar/<int:material_id>/', views.eliminar_material, name='eliminar_material'),

    path('comentarios/', views.listar_comentarios, name='listar_comentarios'),
    path('comentarios/eliminar/<int:comentario_id>/', views.eliminar_comentario, name='eliminar_comentario'),

    path('eliminar_items_carrito/', views.eliminar_items_carrito, name='eliminar_items_carrito'),
    path('panel/', views.panel, name='panel'),
    path('editar_perfil/<int:user_id>/', views.editar_perfil, name='editar_perfil'),
    path('<int:pk>/password/', views.CustomPasswordChangeView.as_view(), name='password_change'),


    path('ubicacion/', views.ubicacion, name='ubicacion'),
    path('ubicacion-nuevas/', views.ubicacion_nuevas, name='ubicacion-nuevas'),
    path('ubicacion-editar/<int:id>/modificar/', views.editar_ubicacion, name='ubicacion-editar'),
    path('ubicacion-eliminar/<int:id>', views.eliminar_ubicacion, name='ubicacion-eliminar'),
    
    path('valoraciones/', views.valoraciones, name='valoraciones'),

    path('ajustes/', views.ajustes, name='ajustes'),

    path('contacto/', views.contacto, name='contacto'),
    path('listarcontacto/', views.mostrar_contacto, name='listarcontacto'),
    path('detallecontacto/<id>/', views.detalle_contacto, name='detallecontacto'),
    path('deletecontacto/<id>/', views.eliminar_contacto, name='deletecontacto'),


    path('solgas/usuario/administrar/', views.usuario_administrar, name='usuarioadministrar'),
    path('solgas/usuario/modificar/<int:id>/',views.usuario_administrar_modificar),
    path('solgas/usuario/eliminar/<int:id>/',views.usuario_administrar_eliminar),
    path('solgas/crearusuario/',views.crear_usuario),

   path('carrucel/', views.carrucel_list, name='carrucel_list'),
    path('carrucel/<int:id>/', views.carrucel_detail, name='carrucel_detail'),
    path('carrucel/create/', views.carrucel_create, name='carrucel_create'),
    path('carrucel/<int:id>/update/', views.carrucel_update, name='carrucel_update'),
    path('carrucel/<int:id>/delete/', views.carrucel_delete, name='carrucel_delete'),

    path('procesar-pago/', views.procesar_pago, name='pago'),
    path('pago-nuevas/', views.agregar_pago, name='pago-nuevas'),
    path('pago-editar/<int:id>/modificar/', views.editar_pago, name='pago_editar'),
    path('pago-eliminar/<int:id>', views.eliminar_pago, name='pago_eliminar'),
    path('administrar-pedidos/', views.administrar_pedidos, name='administrar_pedidos'),
    path('ver-pedido/<int:pedido_id>/', views.VerPedidoView.as_view(), name='ver_pedido'),
    path('modificar-pedido/<int:pedido_id>/', views.ModificarPedidoView.as_view(), name='modificar_pedido'),
]

templates/panel/carrucel/create.html
{% extends "navbar/tienda.html" %}
{% block content %}
<div class="d-flex flex-colum py-4">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-8 mx-auto   - mt-3">
                {% load crispy_forms_tags %}
                <div class="card p-2">
                    <h3 class="   text-center my-2">CARRUCEL</h3>
                    <div class="card body p-2">
                        <form action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %} 

                            <label for="titulo">Titulo:</label>
                            <input type="text" class="form-control"  name="titulo" required><br>
                        
                            <label for="descripcion">Descripcion:</label>
                            <textarea name="descripcion" class="form-control"  required></textarea><br>
                        
                            <label for="imagen">Imagen:</label>
                            <input type="file" class="form-control"  name="imagen" required>                            
                            <div class="d-flex justify-content-end">
                                <a href="{% url 'tienda:carrucel_list' %}" class="btn btn-secondary mt-2 mx-2" button >Cancelar</a>
                                <button type="submit " class="btn btn-danger mt-2 mx-2 " button >Agregar</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>
{% endblock %}

templates/panel/carrucel/delete.html
{% extends "navbar/tienda.html" %}
{% block content %}
<!-- carrucel/delete.html -->
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card">
        <div class="card-header bg-danger text-white">
          <h3 class="mb-0">ELIMINAR CARUCEL</h3>
        </div>
        <div class="card-body">
          <p class="lead">Usted esta seguro de eliminar  "{{ carrucel.titulo }}"?</p>
          <form method="POST" action="{% url 'tienda:carrucel_delete' carrucel.id %}">
            {% csrf_token %}
            <div class="text-center">
              <button type="submit" class="btn btn-danger">Si</button>
              <a href="{% url 'tienda:carrucel_list' %}" class="btn btn-secondary">No</a>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/panel/carrucel/detail.html
{% extends "navbar/tienda.html" %}

{% block content %}
<hr>
<div class="py-1">
  <div class="container">
    <div class="row   ">
      <div class="col-md-12">
        <div class="card " style="width: 50rem;">
          <div class="card-body">
                  <h1 class="mb-0">    
                    Detalles Carucel
                  </h1>
                  <hr>
                  <h3>{{ carrucel.titulo }}</h3>
                  <p>{{ carrucel.descripcion }}</p>
                  <td><img src="{{ carrucel.imagen.url }}" alt="{{ carrucel.titulo }}"  width="700" height="300"></td>
                  <p class="   text-justify">
                    <a class="btn btn-info my-4 mx-auto" href="{% url 'tienda:carrucel_list'  %}">atras</a>
                    <a class="btn btn-dark my-4 mx-auto" href="{% url 'tienda:carrucel_update' carrucel.id %}">Modificar</a>
                    <a class="btn btn-dark my-4 mx-auto" href="{% url 'tienda:carrucel_delete' carrucel.id %}">Eliminar</a>
                  </p>
          </div>
        </div>
    </div>
  </div>  
</div>
{% endblock  %}

templates/panel/carrucel/list.html
<!-- carrucel/list.html -->
{% extends "navbar/tienda.html" %}
{% load static %}

{% block content %}
<div class="container p-3">
  <ul class="nav justify-content-center bg-light">
    <li class="nav-item">
      <a class="nav-link " href="{% url 'tienda:listar_productos' %}">Productos</a>
    </li>
    <li class="nav-item">
      <a class="nav-link " href="{% url 'tienda:mostrar_materiales' %}">Materiales</a>
    </a>
    <li class="nav-item">
      <a class="nav-link " href="{% url 'tienda:listar_categorias' %}">Categorias</a>
    </li>
    <li class="nav-item">
      <a class="nav-link " href="{% url 'tienda:listar_comentarios' %}">Valoraciones</a>
    </li>
    <li class="nav-item">
      <a class="nav-link " href="{% url 'tienda:listarcontacto' %}">Contacto</a>
    </li>
    <li class="nav-item">
      <a class="nav-link " href="/solgas/usuario/administrar">Usuario</a>
    </li>
    <li class="nav-item">
      <a class="nav-link " href="{% url 'tienda:administrar_pedidos' %}">Pedidos</a>
    </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/carrucel">carrucel</a>
    </li> 
  </ul>
</div> 
  
<br>

<div class="d-flex flex-column">
    <div class="container text-center">
      <div class="row justify-content-center">
        <div class="col-lg-12   ">
          <div class="card">
            <div class="card-header text-center font-weight-bold">
              {{ title }}
            </div>
            <div class="card-body table-responsive align-items-center">
              <div class="d-flex justify-content-end mb-2">
                <a href="{% url 'tienda:carrucel_create' %}" class="btn btn-success btn-sm">
                  <i class="bi bi-plus-circle-fill"></i> Añadir Carucel
                </a>
              </div>
              <table class="table">
                <thead>
                  <tr>
                    <th>titulo</th>
                    <th>descripcion</th>
                    <th>imagen</th>
                    <th>Acciones</th>
                  </tr>
                </thead>
                <tbody>
                  {% for carrucel in carruceles %}
                    <tr>
                      <td>{{ carrucel.titulo }}</td>
                      <td>{{ carrucel.descripcion }}</td>
                      <td><img src="{{ carrucel.imagen.url }}" alt="{{ carrucel.titulo }}"  width="50" height="50"></td>
                      <td>
                        <a  class="btn btn-success" href="{% url 'tienda:carrucel_detail' carrucel.id %}">Detalles</a>
                        <a  class="btn btn-warning" href="{% url 'tienda:carrucel_update' carrucel.id %}">Modificar</a>
                        <a  class="btn btn-info" href="{% url 'tienda:carrucel_delete' carrucel.id %}">Eliminar</a>
                      </td>
                    </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

templates/panel/carrucel/update.html
{% extends "navbar/tienda.html" %}
 {% block content %}

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-8 mx-auto   - mt-3">
            {{ mensaje }} {% load crispy_forms_tags %}
            <div class="card p-2">
                <h3 class="   text-center my-2">MODIFICAR CARRUCEL</h3>
                <div class="card body p-2">
                    <form action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <label for="titulo">Titulo:</label>
                        <input type="text" class="form-control" name="titulo" value="{{ carrucel.titulo }}" required><br>
                    
                        <label for="descripcion">Descripcion:</label>
                        <textarea name="descripcion"  class="form-control" required>{{ carrucel.descripcion }}</textarea><br>
                    
                        <label for="imagen">Imagen:</label>
                        <input type="file" class="form-control" name="imagen"><br>
                    
                        <div class="d-flex justify-content-end">
                            <a href="{% url 'tienda:carrucel_list' %}" class="btn btn-secondary mt-2 mx-2" button >Cancelar</a>
                            <button type="submit " class="btn btn-danger mt-2 mx-2 " button >Modificar</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

</div>
{% endblock %}
<!-- carrucel/update.html -->
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <label for="titulo">Titulo:</label>
    <input type="text" name="titulo" value="{{ carrucel.titulo }}" required><br>

    <label for="descripcion">Descripcion:</label>
    <textarea name="descripcion" required>{{ carrucel.descripcion }}</textarea><br>

    <label for="imagen">Imagen:</label>
    <input type="file" name="imagen"><br>

    <input type="submit" value="Update">
</form>

<a href="{% url 'tienda:carrucel_list' %}">Back to List</a>