evaluacion1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('joyeria.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

joyeria/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView
app_name = 'tienda'

urlpatterns = [
    path('', views.index, name='index'),
#Productos
    # Categorias
    path('categorias/', views.ListarCategorias, name='listar_categorias'),
    path('categorias-agregar/', views.AgregarCategoria, name='agregar_categoria'),
    path('categorias/<str:nombre>/modificar/', views.ModificarCategoria, name='modificar_categoria'),  # Cambia de slug a nombre
    path('categorias/<str:nombre>/', views.eliminar_categorias, name='eliminar_categorias'),  # Cambia de slug a nombre
    
    # Productos
    path('producto/<str:nombre>/', views.detalleProducto, name='producto'), 
    path('listar-productos/', views.listar_productos, name='listar_productos'),
    path('agregar-productos/', views.agregar_producto, name='agregar_producto'),
    path('eliminar-productos/<str:nombre>/', views.eliminar_producto, name='eliminar_producto'),  
    path('modificar-productos/<str:nombre>/', views.modificar_producto, name='modificar_producto'),  
    path('productocategoria/<str:nombre>/', views.productoxCategoria, name='productocategoria'), 

#inicio y registro de usuario
    path('registrar/', views.registro, name='registrar'),
    path('login/', views.iniciar_sesion, name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

#carro de compras

    path('addtocart/<int:producto_id>/', views.add_to_cart, name='addtocart'),
    path('cart/', views.cart_page, name='cart'),
    path('procesar_pedido/', views.procesar_pedido, name='procesar_pedido'),
    path('lista-pedidos/', views.lista_pedidos, name='lista_pedidos'),
    path('materiales/', views.mostrar_materiales, name='mostrar_materiales'),
    path('materiales/agregar/', views.agregar_material, name='agregar_material'),
    path('materiales/editar/<int:material_id>/', views.editar_material, name='editar_material'),
    path('materiales/eliminar/<int:material_id>/', views.eliminar_material, name='eliminar_material'),

    path('comentarios/', views.listar_comentarios, name='listar_comentarios'),
    path('comentarios/eliminar/<int:comentario_id>/', views.eliminar_comentario, name='eliminar_comentario'),

    path('eliminar_items_carrito/', views.eliminar_items_carrito, name='eliminar_items_carrito'),
    path('panel/', views.panel, name='panel'),
    path('editar_perfil/<int:user_id>/', views.editar_perfil, name='editar_perfil'),
    path('<int:pk>/password/', views.CustomPasswordChangeView.as_view(), name='password_change'),


    path('ubicacion/', views.ubicacion, name='ubicacion'),
    path('ubicacion-nuevas/', views.ubicacion_nuevas, name='ubicacion-nuevas'),
    path('ubicacion-editar/<int:id>/modificar/', views.editar_ubicacion, name='ubicacion-editar'),
    path('ubicacion-eliminar/<int:id>', views.eliminar_ubicacion, name='ubicacion-eliminar'),
    
    path('valoraciones/', views.valoraciones, name='valoraciones'),

    path('ajustes/', views.ajustes, name='ajustes'),

    path('contacto/', views.contacto, name='contacto'),
    path('listarcontacto/', views.mostrar_contacto, name='listarcontacto'),
    path('detallecontacto/<id>/', views.detalle_contacto, name='detallecontacto'),
    path('deletecontacto/<id>/', views.eliminar_contacto, name='deletecontacto'),


    path('solgas/usuario/administrar/', views.usuario_administrar, name='usuarioadministrar'),
    path('solgas/usuario/modificar/<int:id>/',views.usuario_administrar_modificar),
    path('solgas/usuario/eliminar/<int:id>/',views.usuario_administrar_eliminar),
    path('solgas/crearusuario/',views.crear_usuario),

   path('carrucel/', views.carrucel_list, name='carrucel_list'),
    path('carrucel/<int:id>/', views.carrucel_detail, name='carrucel_detail'),
    path('carrucel/create/', views.carrucel_create, name='carrucel_create'),
    path('carrucel/<int:id>/update/', views.carrucel_update, name='carrucel_update'),
    path('carrucel/<int:id>/delete/', views.carrucel_delete, name='carrucel_delete'),

    path('procesar-pago/', views.procesar_pago, name='pago'),
    path('pago-nuevas/', views.agregar_pago, name='pago-nuevas'),
    path('pago-editar/<int:id>/modificar/', views.editar_pago, name='pago_editar'),
    path('pago-eliminar/<int:id>', views.eliminar_pago, name='pago_eliminar'),
    path('administrar-pedidos/', views.administrar_pedidos, name='administrar_pedidos'),
    path('ver-pedido/<int:pedido_id>/', views.VerPedidoView.as_view(), name='ver_pedido'),
    path('modificar-pedido/<int:pedido_id>/', views.ModificarPedidoView.as_view(), name='modificar_pedido'),
]

templates/categorias/agregar.html
{% extends "navbar/tienda.html" %}
{% block content %}
{% load static %}
{% load crispy_forms_tags %}

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-8 mx-auto mt-3">
            <div class="card p-2">
                <h3 class="text-center my-2">AGREGAR RECETA</h3>
                <div class="card-body p-2">
                    <form action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.media}}
                        {{ form | crispy }}
                        <div class="d-flex justify-content-end">
                            <a href="/categorias" class="btn btn-secondary mt-2 mx-2" button>Cancelar</a>
                            <button type="submit " class="btn btn-danger mt-2 mx-2 " button >Agregar</a>

                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock  %}

templates/categorias/listar.html
{% extends "navbar/tienda.html" %}
{% load static %}
{% block content %}


<div class="container p-3">
  <ul class="nav justify-content-center bg-light">
    <li class="nav-item">
      <a class="nav-link " href="{% url 'tienda:listar_productos' %}">Productos</a>
    </li>
    <li class="nav-item">
      <a class="nav-link " href="{% url 'tienda:mostrar_materiales' %}">Materiales</a>
    </a>
    <li class="nav-item">
      <a class="nav-link " href="{% url 'tienda:listar_categorias' %}">Categorias</a>
    </li>
    <li class="nav-item">
      <a class="nav-link " href="{% url 'tienda:listar_comentarios' %}">Valoraciones</a>
    </li>
    <li class="nav-item">
      <a class="nav-link " href="{% url 'tienda:listarcontacto' %}">Contacto</a>
    </li>
    <li class="nav-item">
      <a class="nav-link " href="/solgas/usuario/administrar">Usuario</a>
    </li>
    <li class="nav-item">
        <a class="nav-link " href="{% url 'tienda:administrar_pedidos' %}">Pedidos</a>
    </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/carrucel">carrucel</a>
    </li> 
  </ul>
</div> 
    
  <div class="d-flex flex-column">
    <div class="container text-center" >
      <div class="row justify-content-center">
        <div class="col-lg-12">
          <div class="card">
            <div class="card-header text-center font-weight-bold">
              <h4>Categorias</h4>
                <form class="flex-grow-1 mr-2 " method="GET" action="{% url 'tienda:listar_categorias' %}">
                  <div class="input-group">
                    <input type="text" class="form-control" placeholder="Buscar materiales..." name="q" value="{{ request.GET.q }}">
                    <div class="input-group-append">
                      <button class="btn btn-outline-secondary" type="submit">Buscar</button>
                    </div>
                  </div>
                </form>
          </div>
          <div class="d-flex justify-content-end mb-2 py-2">
            <a href="/categorias-agregar" class="btn btn-success btn-sm">
              <i class="bi bi-plus-circle-fill"></i> Añadir Categoria
            </a>
          </div>
          <div class="table-responsive">
            <table class="table table-condensed table-hover">
              <thead class=" text-center">

                <tr>
                  <th scope="col">#id</th>
                  <th scope="col">Nombre</th>
                  <th scope="col">imagen</th>
                  <th scope="col">fecha</th>
                  <th colspan="2">Opciones</th>
                </tr>
              </thead>
              <tbody class="text-center ">
                {% for categoria in categorias %}   
                <tr>
                  <td>{{ categoria.id }}</td>
                  <td>
                    <a href="">{{ categoria.nombre }}</a>
                  </td>
                  <td class="zoom">
                    {% if categoria.imagen %}
                      <img src="{{ categoria.imagen.url }}" width="70" height="70">
                    {% else %}
                      No image available
                    {% endif %}
                  </td>
                  <td>{{ categoria.created_at }}</td>
                  <td><a class="btn btn-secondary btn-sm" href="{% url 'tienda:modificar_categoria' categoria.nombre %}" type="button"><i class="bi bi-pencil-square"></i></a>
                  <a class="btn btn-danger btn-sm" href="{% url 'tienda:eliminar_categorias' categoria.nombre %}" type="button"><i class="bi bi-trash-fill"></i></a>
                </tr>
              </tbody>
              {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

templates/categorias/modificar.html
{% extends "navbar/tienda.html" %}
{% block content %}
{% load static %}
{% load crispy_forms_tags %}

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-8 mx-auto mt-3">
            <div class="card p-2">
                <h3 class="text-center my-2">AGREGAR RECETA</h3>
                <div class="card-body p-2">
                    <form action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.media}}
                        {{ form | crispy }}
                        <div class="d-flex justify-content-end">
                            <a href="/categorias" class="btn btn-secondary mt-2 mx-2" button>Cancelar</a>
                            <button type="submit " class="btn btn-danger mt-2 mx-2 " button >Agregar</a>

                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock  %}