evaluacion1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('joyeria.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

joyeria/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView
app_name = 'tienda'

urlpatterns = [
    path('', views.index, name='index'),
#Productos
    # Categorias
    path('categorias/', views.ListarCategorias, name='listar_categorias'),
    path('categorias-agregar/', views.AgregarCategoria, name='agregar_categoria'),
    path('categorias/<str:nombre>/modificar/', views.ModificarCategoria, name='modificar_categoria'),  # Cambia de slug a nombre
    path('categorias/<str:nombre>/', views.eliminar_categorias, name='eliminar_categorias'),  # Cambia de slug a nombre
    
    # Productos
    path('producto/<str:nombre>/', views.detalleProducto, name='producto'), 
    path('listar-productos/', views.listar_productos, name='listar_productos'),
    path('agregar-productos/', views.agregar_producto, name='agregar_producto'),
    path('eliminar-productos/<str:nombre>/', views.eliminar_producto, name='eliminar_producto'),  
    path('modificar-productos/<str:nombre>/', views.modificar_producto, name='modificar_producto'),  
    path('productocategoria/<str:nombre>/', views.productoxCategoria, name='productocategoria'), 

#inicio y registro de usuario
    path('registrar/', views.registro, name='registrar'),
    path('login/', views.iniciar_sesion, name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

#carro de compras

    path('addtocart/<int:producto_id>/', views.add_to_cart, name='addtocart'),
    path('cart/', views.cart_page, name='cart'),
    path('procesar_pedido/', views.procesar_pedido, name='procesar_pedido'),
    path('lista-pedidos/', views.lista_pedidos, name='lista_pedidos'),
    path('materiales/', views.mostrar_materiales, name='mostrar_materiales'),
    path('materiales/agregar/', views.agregar_material, name='agregar_material'),
    path('materiales/editar/<int:material_id>/', views.editar_material, name='editar_material'),
    path('materiales/eliminar/<int:material_id>/', views.eliminar_material, name='eliminar_material'),

    path('comentarios/', views.listar_comentarios, name='listar_comentarios'),
    path('comentarios/eliminar/<int:comentario_id>/', views.eliminar_comentario, name='eliminar_comentario'),

    path('eliminar_items_carrito/', views.eliminar_items_carrito, name='eliminar_items_carrito'),
    path('panel/', views.panel, name='panel'),
    path('editar_perfil/<int:user_id>/', views.editar_perfil, name='editar_perfil'),
    path('<int:pk>/password/', views.CustomPasswordChangeView.as_view(), name='password_change'),


    path('ubicacion/', views.ubicacion, name='ubicacion'),
    path('ubicacion-nuevas/', views.ubicacion_nuevas, name='ubicacion-nuevas'),
    path('ubicacion-editar/<int:id>/modificar/', views.editar_ubicacion, name='ubicacion-editar'),
    path('ubicacion-eliminar/<int:id>', views.eliminar_ubicacion, name='ubicacion-eliminar'),
    
    path('valoraciones/', views.valoraciones, name='valoraciones'),

    path('ajustes/', views.ajustes, name='ajustes'),

    path('contacto/', views.contacto, name='contacto'),
    path('listarcontacto/', views.mostrar_contacto, name='listarcontacto'),
    path('detallecontacto/<id>/', views.detalle_contacto, name='detallecontacto'),
    path('deletecontacto/<id>/', views.eliminar_contacto, name='deletecontacto'),


    path('solgas/usuario/administrar/', views.usuario_administrar, name='usuarioadministrar'),
    path('solgas/usuario/modificar/<int:id>/',views.usuario_administrar_modificar),
    path('solgas/usuario/eliminar/<int:id>/',views.usuario_administrar_eliminar),
    path('solgas/crearusuario/',views.crear_usuario),

   path('carrucel/', views.carrucel_list, name='carrucel_list'),
    path('carrucel/<int:id>/', views.carrucel_detail, name='carrucel_detail'),
    path('carrucel/create/', views.carrucel_create, name='carrucel_create'),
    path('carrucel/<int:id>/update/', views.carrucel_update, name='carrucel_update'),
    path('carrucel/<int:id>/delete/', views.carrucel_delete, name='carrucel_delete'),

    path('procesar-pago/', views.procesar_pago, name='pago'),
    path('pago-nuevas/', views.agregar_pago, name='pago-nuevas'),
    path('pago-editar/<int:id>/modificar/', views.editar_pago, name='pago_editar'),
    path('pago-eliminar/<int:id>', views.eliminar_pago, name='pago_eliminar'),
    path('administrar-pedidos/', views.administrar_pedidos, name='administrar_pedidos'),
    path('ver-pedido/<int:pedido_id>/', views.VerPedidoView.as_view(), name='ver_pedido'),
    path('modificar-pedido/<int:pedido_id>/', views.ModificarPedidoView.as_view(), name='modificar_pedido'),
]

templates/panel/contacto/contacto.html
{% extends "navbar/tienda.html" %}

{% block content %}
<br>
<div class="container">
    <h5 class="-0.2s text-center">CONTACTO</h5>
    <div class="row">
        <div class="col-lg-6 offset-lg-0 col-sm-12 mx-auto">
            {% load crispy_forms_tags %}
            <form method="post" action="">
                {% csrf_token %} {{ form | crispy }}
                <div class="justify-content-center">
                    <button type="reset" class="btn btn-secondary mt-1 mx-2">Cancelar</button>
                    <button type="submit" class="btn btn-danger mt-1">Enviar</button>
                </div>
            </form>
            <!-- Icons -->
        </div>
        <div class="col-lg-6 rounded embed-responsive embed-responsive-4by3 p-3">
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3064.3273489664516!2d-73.21453172400344!3d-39.82207775146552!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x9615ee915265860b%3A0x45d14ebfe7bdb8fe!2sBolivia%20134%2C%20Valdivia%2C%20Los%20R%C3%ADos!5e0!3m2!1ses!2scl!4v1700481418517!5m2!1ses!2scl" width="500" height="400" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>    
        </div>
    </div>
</div>
{% endblock %}

templates/panel/contacto/detalle.html
{% extends "navbar/tienda.html" %}

{% block content %}
<hr>
<div class="">
  <div class="container">
      <div class="row   ">
          <div class="col-md-12">
              <div class="card  shadow producto_data">
                  <div class="card-body "> 
                  <h1 class="mb-0">    
                    Detalles MASCOTA
                  </h1>
                  <hr>
                  <p><b> ID :</b>   {{ contacto.id }}</p>
                  <p><b> NOMBRE :</b>  {{ contacto.nombre }}</p>
                  <p><b> tipo :</b>  {{ contacto.correo }}</p>                    
                  <p><b> mensaje :</b>  {{ contacto.mensaje }}</p>     
                  <p class="   text-justify">
                    <a href="/listarcontacto" class="btn btn-dark my-4 mx-auto">Atras</a>
                  </p>               
                </div>
              </div>
          </div>
      </div>
  </div>
</div>
{% endblock  %}

templates/panel/contacto/mostrar.html
{% extends "navbar/tienda.html" %}
{% load static %} 

{% block content %}

<br>

<div class="container p-3">
  <ul class="nav justify-content-center bg-light">
    <li class="nav-item">
      <a class="nav-link " href="{% url 'tienda:listar_productos' %}">Productos</a>
    </li>
    <li class="nav-item">
      <a class="nav-link " href="{% url 'tienda:mostrar_materiales' %}">Materiales</a>
    </a>
    <li class="nav-item">
      <a class="nav-link " href="{% url 'tienda:listar_categorias' %}">Categorias</a>
    </li>
    <li class="nav-item">
      <a class="nav-link " href="{% url 'tienda:listar_comentarios' %}">Valoraciones</a>
    </li>
    <li class="nav-item">
      <a class="nav-link " href="{% url 'tienda:listarcontacto' %}">Contacto</a>
    </li>
    <li class="nav-item">
      <a class="nav-link " href="/solgas/usuario/administrar">Usuario</a>
    </li>
    <li class="nav-item">
      <a class="nav-link " href="{% url 'tienda:administrar_pedidos' %}">Pedidos</a>
    </a>
    </li>
  </ul>
</div>

<br>

<div class="d-flex flex-column">
  <div class="container text-center">
    <div class="row justify-content-center">
      <div class="col-lg-12   ">
        <div class="card">

          <div class="card-header text-center font-weight-bold">
            {{ title }}
          </div>
          <div class="card-body table-responsive align-items-center">
            <div class="d-flex justify-content-end mb-2">
              <form class="flex-grow-1 mr-2 py-2" method="GET" action="{% url 'tienda:listarcontacto' %}">
                <div class="input-group">
                  <input type="text" class="form-control" placeholder="Buscar producto..." name="q" value="{{ request.GET.q }}">
                  <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="submit">Buscar</button>
                  </div>
                </div>
              </form>
            </div>
            <table class="table">
              <thead>
                <tr>
                  <th>id</th>
                  <th>Nombre</th>
                  <th>Correo</th>
                  <th>Mensaje</th>
                  <th>opcion</th>
                </tr>
              </thead>
              <tbody>
                {% for contac in contacto %}
                <tr>
                  <td>{{ contac.id }}</td>
                  <td><a href="{% url 'tienda:detallecontacto' contac.id %}">{{ contac.nombre }}</td>
                  <td>{{ contac.correo }}</td>
                  <td>{{ contac.mensaje }}</td>
                  <td>
                      <a class="btn btn-danger btn-sm" href="{% url 'tienda:deletecontacto' contac.id %}" type="button"><i class="bi bi-trash-fill"></i></a>
                  </td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock  %}