evaluacion1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('joyeria.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

joyeria/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView
app_name = 'tienda'

urlpatterns = [
    path('', views.index, name='index'),
#Productos
    # Categorias
    path('categorias/', views.ListarCategorias, name='listar_categorias'),
    path('categorias-agregar/', views.AgregarCategoria, name='agregar_categoria'),
    path('categorias/<str:nombre>/modificar/', views.ModificarCategoria, name='modificar_categoria'),  # Cambia de slug a nombre
    path('categorias/<str:nombre>/', views.eliminar_categorias, name='eliminar_categorias'),  # Cambia de slug a nombre
    
    # Productos
    path('producto/<str:nombre>/', views.detalleProducto, name='producto'), 
    path('listar-productos/', views.listar_productos, name='listar_productos'),
    path('agregar-productos/', views.agregar_producto, name='agregar_producto'),
    path('eliminar-productos/<str:nombre>/', views.eliminar_producto, name='eliminar_producto'),  
    path('modificar-productos/<str:nombre>/', views.modificar_producto, name='modificar_producto'),  
    path('productocategoria/<str:nombre>/', views.productoxCategoria, name='productocategoria'), 

#inicio y registro de usuario
    path('registrar/', views.registro, name='registrar'),
    path('login/', views.iniciar_sesion, name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

#carro de compras

    path('addtocart/<int:producto_id>/', views.add_to_cart, name='addtocart'),
    path('cart/', views.cart_page, name='cart'),
    path('procesar_pedido/', views.procesar_pedido, name='procesar_pedido'),
    path('lista-pedidos/', views.lista_pedidos, name='lista_pedidos'),
    path('materiales/', views.mostrar_materiales, name='mostrar_materiales'),
    path('materiales/agregar/', views.agregar_material, name='agregar_material'),
    path('materiales/editar/<int:material_id>/', views.editar_material, name='editar_material'),
    path('materiales/eliminar/<int:material_id>/', views.eliminar_material, name='eliminar_material'),

    path('comentarios/', views.listar_comentarios, name='listar_comentarios'),
    path('comentarios/eliminar/<int:comentario_id>/', views.eliminar_comentario, name='eliminar_comentario'),

    path('eliminar_items_carrito/', views.eliminar_items_carrito, name='eliminar_items_carrito'),
    path('panel/', views.panel, name='panel'),
    path('editar_perfil/<int:user_id>/', views.editar_perfil, name='editar_perfil'),
    path('<int:pk>/password/', views.CustomPasswordChangeView.as_view(), name='password_change'),


    path('ubicacion/', views.ubicacion, name='ubicacion'),
    path('ubicacion-nuevas/', views.ubicacion_nuevas, name='ubicacion-nuevas'),
    path('ubicacion-editar/<int:id>/modificar/', views.editar_ubicacion, name='ubicacion-editar'),
    path('ubicacion-eliminar/<int:id>', views.eliminar_ubicacion, name='ubicacion-eliminar'),
    
    path('valoraciones/', views.valoraciones, name='valoraciones'),

    path('ajustes/', views.ajustes, name='ajustes'),

    path('contacto/', views.contacto, name='contacto'),
    path('listarcontacto/', views.mostrar_contacto, name='listarcontacto'),
    path('detallecontacto/<id>/', views.detalle_contacto, name='detallecontacto'),
    path('deletecontacto/<id>/', views.eliminar_contacto, name='deletecontacto'),


    path('solgas/usuario/administrar/', views.usuario_administrar, name='usuarioadministrar'),
    path('solgas/usuario/modificar/<int:id>/',views.usuario_administrar_modificar),
    path('solgas/usuario/eliminar/<int:id>/',views.usuario_administrar_eliminar),
    path('solgas/crearusuario/',views.crear_usuario),

   path('carrucel/', views.carrucel_list, name='carrucel_list'),
    path('carrucel/<int:id>/', views.carrucel_detail, name='carrucel_detail'),
    path('carrucel/create/', views.carrucel_create, name='carrucel_create'),
    path('carrucel/<int:id>/update/', views.carrucel_update, name='carrucel_update'),
    path('carrucel/<int:id>/delete/', views.carrucel_delete, name='carrucel_delete'),

    path('procesar-pago/', views.procesar_pago, name='pago'),
    path('pago-nuevas/', views.agregar_pago, name='pago-nuevas'),
    path('pago-editar/<int:id>/modificar/', views.editar_pago, name='pago_editar'),
    path('pago-eliminar/<int:id>', views.eliminar_pago, name='pago_eliminar'),
    path('administrar-pedidos/', views.administrar_pedidos, name='administrar_pedidos'),
    path('ver-pedido/<int:pedido_id>/', views.VerPedidoView.as_view(), name='ver_pedido'),
    path('modificar-pedido/<int:pedido_id>/', views.ModificarPedidoView.as_view(), name='modificar_pedido'),
]

templates/navbar/tienda.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}JOYERIA{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-3+MhwzvZpLCkbCIshkFVl+5T4mOWjYbERXVILZ9WfDo2MHkkKFnOpN+FFOvKw03CIOa6p1cZ1vfW/T9QsPVrMg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="{% static 'css/custom.css' %}" rel="stylesheet" type="text/css"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="shortcut icon" type="image/x-icon" href="{% static "icono.ico" %}">
    <style>
      body {
        display: flex;
        flex-direction: column;
        min-height: 100vh; /* This ensures the content takes at least the full height of the viewport */
      }
    
      footer {
        margin-top: auto; /* Push the footer to the bottom */
      }
    </style>
  </head>
  {% load crispy_forms_tags %}

  <body >
    <div class="container  d-flex justify-content-center align-items-center">
      <img src="{% static 'images/icono.png' %}" alt="Logo" width="500" height="150">
    </div>
    
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">
          <img src="{% static 'images/icono.png' %}" alt="Logo" width="100" height="50">
        </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
              <div class="navbar-nav mx-auto text-center">
                  {% for categoria in categorias %}
                      <a class="nav-link" href="{% url 'tienda:productocategoria' categoria.nombre %}">
                          {{categoria.nombre}}
                      </a>
                  {% endfor %}
                  {% if user.is_staff %}
                      <a class="nav-item nav-link" aria-current="page" href="/panel">Panel de Control</a>
                  {% endif %}
                  <a class="nav-item nav-link active" aria-current="page" href="/contacto">Contacto</a>
              </div>
              <div class="navbar-nav ml-auto">
                  {% if user.is_authenticated %}
                      <a href="{% url 'tienda:cart' %}" class="btn nav-link">
                        <div class="d-flex flex-column align-items-center">
                          <i class="bi-cart-fill" style='color:#e11212'></i>
                          <span>Carro</span>
                      </div>
                      </a>
                      <li class="nav-item dropdown">
                          <a class="nav-link" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                              <div class="d-flex flex-column align-items-center">
                                  <i class="bi bi-person-fill" style='color:#e11212'></i>
                                  <span>{{ user.username }}</span>
                              </div>
                          </a>
                          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{% url 'tienda:lista_pedidos' %}">pedido</a>
                            <a class="dropdown-item" href="{% url 'tienda:pago' %}">Pago</a>
                              <a class="dropdown-item" href="{% url 'tienda:ubicacion' %}">Ubicación</a>
                              <a class="dropdown-item" href="{% url 'tienda:valoraciones' %}">Valoraciones</a>
                              <a class="dropdown-item" href="{% url 'tienda:ajustes' %}">Ajustes</a>
                              <div class="dropdown-divider"></div>
                              <a class="dropdown-item" href="{% url 'logout' %}">Cerrar Sesión</a>
                          </div>
                      </li>
                  {% else %}
                      <a class="nav-item nav-link active" aria-current="page" href="/login">
                          <div class="d-flex flex-column align-items-center">
                              <i class="bi bi-person-fill" style='color:#e11212'></i>
                              <span>Ingresar</span>
                          </div>
                      </a>
                      <a class="nav-item nav-link active" aria-current="page" href="/registrar">
                          <div class="d-flex flex-column align-items-center">
                              <i class="bi bi-person-fill" style='color:#e11212'></i>
                              <span>Registrar</span>
                          </div>
                      </a>
                  {% endif %}
              </div>
          </div>
      </div>
  </nav>
  
<section>
    {% block content  %}
    {% endblock %}
</section>
<!-- Pie de página -->
<footer class="container-fluid text-white text-center text-lg-start mt-auto" style="background-color: #808080;">
  <div class="row mt-1">
    <div class="col-lg-4 col-md-4">
      <h5 class="text-uppercase">Enlaces rápidos</h5>
      <ul class="list-unstyled my-auto mx-auto text-center">
        {% if user.is_authenticated %}
          <!-- Mostrar información específica para usuarios autenticados -->
          <li>
            <i class="bi bi-house-door-fill"><span>Perfil, {{ user.username }} </span></i>
          </li>
          <li>
            <i class="bi bi-facebook"></i><a class="text-white" href="{% url 'tienda:cart' %}">Carro</a>
          </li>
        {% else %}
          <!-- Mostrar información alternativa para usuarios no autenticados -->
          <li>
            <!-- Agrega aquí la información alternativa para usuarios no autenticados -->
          </li>
          <li>
            <!-- Agrega aquí la información alternativa para usuarios no autenticados -->
          </li>
        {% endif %}
        <li>
          <span><i class="bi bi-telephone-plus-fill"></i></span><a class="text-white" href="{% url 'tienda:contacto' %}"><span>Contacto</span></a>
        </li>
      </ul>
    </div>
    <div class="col-lg-4 col-md-4">
      <!-- Nueva columna para la imagen -->
      <div class="container d-flex justify-content-center align-items-center">
        <img src="{% static 'images/icono.png' %}" alt="Logo" width="300" height="90">
      </div>
    </div>
    <div class="col-lg-4 col-md-4">
      <h5 class="text-uppercase">Contactos</h5>
      <ul class="list-unstyled my-auto mx-auto text-center">
        <li>
          <i class="bi bi-house-door-fill"><span>147 Bolivia Valdivia, Los Ríos</span></i>
        </li>
        <li>
          <i class="bi bi-facebook"></i><a class="text-white" href="">Joyeria Alyssum </a>
        </li>
        <li>
          <span><i class="bi bi-telephone-plus-fill"></i></span><span>(+56) 9 8995 4220</span>
        </li>
      </ul>
    </div>
  </div>
  <div class="container-fluid text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2023 Kels:
    <a class="text-white" href="https://www.instagram.com/kels.sepulveda_/">Kels.sepulveda_</a>
  </div>
</footer>

    
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-y1+kVgvcX/7EQb6an3kK9b9gKbT+rGkE4s+j+c5BtLOb5X8ivn4aZLXCedCzidL5k12K96JzMFxje4k7DjxBRQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <!-- MESSAGES-->
    {% if messages %} {% for message in messages %}
    <script>
        Swal.fire({
            "text": "{{ message }}",
            "icon": "success"
        })
    </script>
    {% endfor %} {% endif %}
    <!-- END MESSAGES -->
  </body>
</html>